query PriorityMatrix {
  priorityMatrix {
    urgentImportant {
      id
      title
      status
      urgency
      impact
      deadline
      assignee
      recurrenceId
      occurrenceDate
      isRecurring
      project {
        name
      }
    }
    important {
      id
      title
      status
      urgency
      impact
      deadline
      assignee
      recurrenceId
      occurrenceDate
      isRecurring
      project {
        name
      }
    }
    urgent {
      id
      title
      status
      urgency
      impact
      deadline
      assignee
      recurrenceId
      occurrenceDate
      isRecurring
      project {
        name
      }
    }
    neither {
      id
      title
      status
      urgency
      impact
      deadline
      assignee
      recurrenceId
      occurrenceDate
      isRecurring
      project {
        name
      }
    }
  }
}
